AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Lambda REST API with Serverless Aurora DB CI/CD Pipeline
Resources:
  DbSubnet:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Sub '${AuroraDBName}-subnet-group'
      DBSubnetGroupDescription: 'Subnet group to allow communication between Lambda and Aurora'
      SubnetIds:
      - !Ref VpcSubnet1
      - !Ref VpcSubnet2
  
  AuroraDB:
    Type: "AWS::RDS::DBCluster"
    Properties:
      Engine: aurora
      EngineMode: serverless
      DatabaseName: !Ref AuroraDBName
      MasterUsername: !Ref AuroraDBUser
      MasterUserPassword: !Ref AuroraDBPassword
      DBClusterIdentifier: !Sub '${AWS::StackName}-db'
      VpcSecurityGroupIds:
        - !Ref VpcSecGroup
      DBSubnetGroupName: !Ref DbSubnet
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 2
        SecondsUntilAutoPause: !Ref AwakeInterval
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-UserPool'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub '${AWS::StackName}-client'
      GenerateSecret: false
  CBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      Policies:
      - PolicyName: codebuild-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
          Version: '2012-10-17'
  CFRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      Policies:
      - PolicyName: pipeline-cloudformation-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Resource: "*"
            Action:
            - "apigateway:*"
            - "codedeploy:*"
            - "lambda:*"
            - "cloudfront:*"
            - "route53:*"
            - "ec2:*"
            - "cloudformation:CreateChangeSet"
            - "iam:GetRole"
            - "iam:CreateRole"
            - "iam:DeleteRole"
            - "iam:PutRolePolicy"
            - "iam:AttachRolePolicy"
            - "iam:DeleteRolePolicy"
            - "iam:DetachRolePolicy"
            - "iam:PassRole"
            - "s3:GetObjectVersion"
            - "s3:GetBucketVersioning"
          Version: '2012-10-17'
  CPRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
            - codebuild:*
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - s3:*
            - cloudformation:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  CPBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  CBProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-Build'
      Description: !Sub 'Build project for the ${AWS::StackName} stack.'
      ServiceRole: !GetAtt CBRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/nodejs:8.11.0'
        EnvironmentVariables:
            - Name: 'DB_HOST'
              Value: !GetAtt AuroraDB.Endpoint.Address
            - Name: 'DB_NAME'
              Value: !Ref AuroraDBName
            - Name: 'DB_USER'
              Value: !Ref AuroraDBUser
            - Name: 'DB_PASS'
              Value: !Ref AuroraDBPassword
            - Name: 'CG_USER_POOL_ARN'
              Value: !GetAtt CognitoUserPool.Arn
            - Name: 'S3_BUCKET'
              Value: !Ref CPBucket
            - Name: 'ACM_CERT'
              Value: !Ref CrtArn
            - Name: 'APIGW_SUB_DOMAIN'
              Value: !Ref APISubDomain
            - Name: 'APIGW_ROOT_DOMAIN'
              Value: !Ref RootDomain  
            - Name: 'VPC_ID'
              Value: !Ref VpcId
            - Name: 'VPC_SUBNET_1'
              Value: !Ref VpcSubnet1
            - Name: 'VPC_SUBNET_2'
              Value: !Ref VpcSubnet2
            - Name: 'VPC_SEC_GROUP'
              Value: !Ref VpcSecGroup   
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
    DependsOn:
      - CBRole
      - CPBucket
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt CPRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CPBucket
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifacts
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubKey
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifacts
              OutputArtifacts:
                - Name: DeploymentArtifacts
              Configuration:
                ProjectName: !Ref CBProject
              RunOrder: 1
        - Name: DeployToLambda
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: DeploymentArtifacts
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub '${AWS::StackName}-ci-cd-stack'
                ChangeSetName: !Sub '${AWS::StackName}-ci-cd-changeset'
                TemplatePath: DeploymentArtifacts::outputtemplate.yml
                TemplateConfiguration: DeploymentArtifacts::templateconfig.json
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt CFRole.Arn
              RunOrder: 1
            - Name: UpdateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: DeploymentArtifacts
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: !Sub '${AWS::StackName}-ci-cd-stack'
                ChangeSetName: !Sub '${AWS::StackName}-ci-cd-changeset'
              RunOrder: 2
    DependsOn:
      - CBProject
      - CPRole
      - CPBucket
      - CFRole
Parameters:
  APISubDomain:
    Type: String
  RootDomain:
    Type: String
    Default: nastojte.cz
  CrtArn:
    Type: String
    Description: ARN of the ACM certificate for the CloudFront distribution for the API
    Default: >-
      arn:aws:acm:us-east-1:422001608153:certificate/1a07bc14-ecd5-4998-bfaa-2431c41f6642
  GitHubRepo:
    Type: String
    Description: GitHub repository
  GitHubUser:
    Type: String
    Description: GitHub repo owner
    Default: oookoook
  GitHubKey:
    Type: String
    Description: GitHub API Key
  GitHubBranch:
    Type: String
    Description: GitHub branch to deploy from
    Default: master
  AuroraDBName:
    Type: String
    Description: Name for the created database. Must begin with a letter and contain only alphanumeric characters.
  AuroraDBUser:
    Type: String
    Description: Username for the newly created DB user
  AwakeInterval:
    Type: String
    Description: Interval in minutes after which the DB goes to sleep.
    Default: 1800
  AuroraDBPassword:
    Type: String
    Description: Password that will be used for the newly created DB user
  VpcId:
    Type: String
    Description: VPC Id that is used to connect to the Aurora DB (the Aurora DB is created in the default VPC)
    Default: vpc-227e4049
  VpcSubnet1:
    Type: String
    Description: Subnet Id that is used to connect to the Aurora DB
  VpcSubnet2:
    Type: String
    Description: Subnet Id that is used to connect to the Aurora DB
  VpcSecGroup:
    Type: String
    Description: Security group Id that is used to connect to the Aurora DB
    Default: sg-947393fa 
Outputs:
  AuroraDBEndpoint:
    Value: !GetAtt AuroraDB.Endpoint.Address
    Description: DBEndpoint
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Description: Cognito User Pool ID
  CognitoUserPoolArn:
    Value: !GetAtt CognitoUserPool.Arn
    Description: Cognito User Pool Arn
  CognitoClient:
    Value: !Ref CognitoUserPoolClient
    Description: Cognito Client ID
  BackendUrl:
    Value: !Sub 'https://${APISubDomain}.${RootDomain}'
    Description: URL of the backend api.


